baseURL = "https://dental-amb.netlify.app/"
languageCode = "hr"
defaultContentLanguage = "hr"
title = "Poliklinika Optima"
theme = "alpha-church"
customCSS = ["/css/custom.css"]
google_fonts = ''

rssLimit = 5
pagination.pagerSize = 4

enableEmoji = true
enableRobotsTXT = true

[languages]
  [languages.hr]
    languageName = "Hrvatski"
    weight = 1

  [languages.en]
    languageName = "English"
    weight = 2


# Enter your tracking code to enable Google Analytics
[services]
  [services.googleAnalytics]
    ID = ""

[security]
  enableInlineShortcodes = true

[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  tag = "tags"
  preacher = "preachers"
  series = "series"

[params]
  title = "Poliklinika Optima"
  subtitle = "Oftalmologija i strabologija u srcu Splita"
  keywords = ["oftalmologija", "strabologija", "očna poliklinika", "pregled vida", "Split"]
  languageCode = "hr" 
  instant_page = true


  [params.author]
    name = "tkulic"
    email = "toni.kulic@yahoo.com"

  [params.favicon]
    sml = "./img/favicon/favicon-16x16.png"
    med = "./img/favicon/favicon-32x32.png"
    #lge = "example96.png"

  [params.banner]
    image = "./img/dentist-2530983_1280.jpg"

  [params.map]
    service = "osm"
    # For Open Street Map widgets
    latitude = "43.5053624"
    longitude = "16.4617637"
    zoom = "16"

  [params.contact]
    #For netlify, please read https://www.netlify.com/docs/form-handling/
    service = "netlify"
    confirm_page = "/kontakt"
    text = "Posjetite nas u ulici Šoltanska 26, 21000 Split, ili nam se javite izravno:"
    phone = "021 370 642"
    mail = "info@poliklinikaoptima.hr"

  [params.footer]
    copyright = ["© Poliklinika Optima",
                   "Built by [tkulic](https://github.com/tkulic)",
                   "Built with [hugo](https://gohugo.io/)"
                  ]

  [[params.links]]
    service = "Instagram"
    icon = "fa-instagram"
    icon_pack = "fab"
    link = "https://www.instagram.com/optima.poliklinika/?hl=hr"

[[menu.main]]
  name = "Početna"
  url = "/"
  weight = 1

[[menu.main]]
  name = "O nama"
  url = "/onama/"
  weight = 2

[[menu.main]]
  name = "Usluge"
  url = "/usluge/"
  weight = 3

[[menu.main]]
  name = "Kontakt"
  url = "/kontakt"
  weight = 4

